spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authsecret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG