spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080